server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;
    server_name www.saotie.com;
    charset utf-8;
    index index.php index.html index.htm default.php default.htm default.html;
    access_log /www/sites/www.saotie.com/log/access.log main;
    error_log /www/sites/www.saotie.com/log/error.log;

    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md) {
        return 404;
    }

    location ^~ /.well-known/acme-challenge {
        allow all;
        root /usr/share/nginx/html;
    }

    if ($uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$") {
        return 403;
    }

    root /www/sites/www.saotie.com/index;
    http2 on;
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }

    ssl_certificate /www/sites/saotie.com/ssl/fullchain.pem;
    ssl_certificate_key /www/sites/saotie.com/ssl/privkey.pem;
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497 https://$host$request_uri;
    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /404.html;
}
